export const PRODUCTS_INIT_START = 'PRODUCTS_INIT_START';
export const PRODUCTS_INIT_START_LOADING = 'PRODUCTS_INIT_START_LOADING';
export const PRODUCTS_INIT_SUCCESS = 'PRODUCTS_INIT_SUCCESS';
export const PRODUCTS_INIT_FAIL = 'PRODUCTS_INIT_FAIL';

export const ADD_TO_CART = "ADD_TO_CART";